eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
from: git-default-1.0